FROM registry.access.redhat.com/ubi9/python-311:1-62.1716478620
WORKDIR /opt/app-root/src/converter

USER root
RUN dnf install -y diffutils \
 && chown -R default:root /opt/app-root/src/converter

USER default
RUN git clone https://github.com/ggerganov/llama.cpp.git \
 && cd llama.cpp/ && make \
 && pip install -r requirements.txt

COPY . /opt/app-root/src/converter/

RUN pip install -r requirements.txt

ENTRYPOINT ["sh", "run.sh"]
